### ISSUE TITLE
Support bgen

### ISSUE THREAD

**Issue by fpcasale** [limix/geno-sugar#5]
Add support and examples from bgen genotypes imported using the bgen reader

**Comment by horta** [comment]
https://github.com/limix/geno-sugar/commit/e30447d508eb549efcf85bb0369876ceca0635f8
Why did you modify the examples back to the original form? I modify them to support documentation test, now the plink example is not being tested anymore.

**Comment by horta** [comment]
Sorry about that! Let me finish this. Should be easy.
